import { MenuItem, MenuCategory } from './types';

export const MENU_CATEGORIES: MenuCategory[] = [
  { id: 'cocktails', name: 'Cocktails', label: 'COCKTAILS', count: 0 },
  { id: 'mocktails', name: 'Mocktails', label: 'MOCKTAILS', count: 0 },
  { id: 'cognacs-whiskeys', name: 'Cognacs & Whiskeys', label: 'COGNACS & WHISKEYS', count: 0 },
  { id: 'tequila', name: 'Tequila', label: 'TEQUILA', count: 0 },
  { id: 'red-wine-champagne', name: 'Red Wine & Champagne', label: 'RED WINE & CHAMPAGNE', count: 0 },
  { id: 'beer-soft-drinks-water', name: 'Beer, Soft Drinks & Water', label: 'BEER, SOFT DRINKS & WATER', count: 0 },
  { id: 'energy-drinks', name: 'Energy Drinks', label: 'ENERGY DRINKS', count: 0 },
];

export const MENU_ITEMS: MenuItem[] = [
  // Cocktails
  { id: 'pornstar-martini', name: 'Pornstar Martini', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 10000, category: 'cocktails', image: new URL('./assets/product-images/pornstar-martini.jpg', import.meta.url).href },
  { id: 'pina-colada', name: 'Pina Colada', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/pina-colada.jpg', import.meta.url).href },
  { id: 'screw-driver', name: 'Screw Driver', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/screw-driver.jpg', import.meta.url).href },
  { id: 'sex-on-the-beach', name: 'Sex on the Beach', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/sex-on-the-beach.jpg', import.meta.url).href },
  { id: 'long-island-ice-tea', name: 'Long Island Ice Tea', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/long-island-ice-tea.jpg', import.meta.url).href },
  { id: 'adios-motherfucker', name: 'Adios Motherfucker', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/adios-motherfucker.jpg', import.meta.url).href },
  { id: 'chapman-alcoholic', name: 'Chapman (Alcoholic)', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/chapman-alcoholic.jpg', import.meta.url).href },
  { id: 'special-cocktails', name: 'Special Cocktails', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 12000, category: 'cocktails', image: new URL('./assets/product-images/special-cocktails.jpg', import.meta.url).href },
  { id: 'tequila-sunrise', name: 'Tequila Sunrise', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/tequila-sunrise.jpg', import.meta.url).href },
  { id: 'old-fashioned', name: 'Old Fashioned', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/old-fashioned.jpg', import.meta.url).href },
  { id: 'blue-hawaiian-cocktail', name: 'Blue Hawaiian', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/blue-hawaiian-cocktail.jpg', import.meta.url).href },
  { id: 'strawberry-daiquiri', name: 'Strawberry Daiquiri', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/strawberry-daiquiri.jpg', import.meta.url).href },
  { id: 'classic-daiquiri', name: 'Classic Daiquiri', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 8000, category: 'cocktails', image: new URL('./assets/product-images/classic-daiquiri.jpg', import.meta.url).href },
  { id: 'margarita', name: 'Margarita', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/margarita.jpg', import.meta.url).href },
  { id: 'mojito', name: 'Mojito', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 9000, category: 'cocktails', image: new URL('./assets/product-images/mojito.jpg', import.meta.url).href },
  { id: 'tequila-shot', name: 'Tequila Shot', description: 'A Backroom Lounge pour curated for classy evenings, soft conversation, and the Osogbo after-dark mood.', price: 3000, category: 'cocktails', image: new URL('./assets/product-images/tequila-shot.jpg', import.meta.url).href },
  // Mocktails
  { id: 'frozen-virgin-colada', name: 'Frozen Virgin Colada', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/frozen-virgin-colada.jpg', import.meta.url).href },
  { id: 'blue-lagoon-cream', name: 'Blue Lagoon in Cream', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/blue-lagoon-cream.jpg', import.meta.url).href },
  { id: 'mango-bull', name: 'Mango Bull', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/mango-bull.jpg', import.meta.url).href },
  { id: 'alice-mocktails', name: 'Alice Mocktails', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 9000, category: 'mocktails', image: new URL('./assets/product-images/alice-mocktails.jpg', import.meta.url).href },
  { id: 'kiwi-cooler', name: 'Kiwi Cooler', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 9000, category: 'mocktails', image: new URL('./assets/product-images/kiwi-cooler.jpg', import.meta.url).href },
  { id: 'tropical-island', name: 'Tropical Island', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/tropical-island.jpg', import.meta.url).href },
  { id: 'strawberry-coconut', name: 'Strawberry Coconut', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/strawberry-coconut.jpg', import.meta.url).href },
  { id: 'chapman-mocktail', name: 'Chapman', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/chapman-mocktail.jpg', import.meta.url).href },
  { id: 'blue-hawaiian-mocktail', name: 'Blue Hawaiian', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/blue-hawaiian-mocktail.jpg', import.meta.url).href },
  { id: 'strawberry-daiquiri-mock', name: 'Strawberry Daiquiri', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/strawberry-daiquiri-mock.jpg', import.meta.url).href },
  { id: 'milk-shakes-smoothies', name: 'Milk Shakes and Smoothies', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 8000, category: 'mocktails', image: new URL('./assets/product-images/milk-shakes-smoothies.jpg', import.meta.url).href },
  { id: 'fresh-juices', name: 'Fresh Juices', description: 'A no-alcohol refreshment for calm hangouts, reflective pauses, and easy lounge moments.', price: 5000, category: 'mocktails', image: new URL('./assets/product-images/fresh-juices.jpg', import.meta.url).href },
  // Cognacs & Whiskeys
  { id: 'hennessy-vsop', name: 'Hennessy VSOP', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 150000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/hennessy-vsop.jpg', import.meta.url).href },
  { id: 'hennessy-vs', name: 'Hennessy VS', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 85000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/hennessy-vs.jpg', import.meta.url).href },
  { id: 'martell-vsop', name: 'Martell VSOP', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 130000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/martell-vsop.jpg', import.meta.url).href },
  { id: 'martell-vs', name: 'Martell VS', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 80000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/martell-vs.jpg', import.meta.url).href },
  { id: 'jack-daniels', name: "Jack Daniel's", description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 50000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/jack-daniels.jpg', import.meta.url).href },
  { id: 'red-label', name: 'Red Label', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 30000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/red-label.jpg', import.meta.url).href },
  { id: 'william-lawson', name: 'William Lawson', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 25000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/william-lawson.jpg', import.meta.url).href },
  { id: 'glenfiddich', name: 'Glenfiddich', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 200000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/glenfiddich.jpg', import.meta.url).href },
  { id: 'jameson-green', name: 'Jameson (Green)', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 40000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/jameson-green.jpg', import.meta.url).href },
  { id: 'jameson-black-barrel', name: 'Jameson Black Barrel', description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 60000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/jameson-black-barrel.jpg', import.meta.url).href },
  { id: 'dusse', name: "D'usse", description: 'A premium bottle selection for unhurried conversations, private corners, and refined Backroom Lounge nights.', price: 110000, category: 'cognacs-whiskeys', image: new URL('./assets/product-images/dusse.jpg', import.meta.url).href },
  // Tequila
  { id: 'don-julio', name: 'Don Julio', description: 'A bold bottle selection for celebratory groups, curated hangouts, and confident lounge energy.', price: 600000, category: 'tequila', image: new URL('./assets/product-images/don-julio.jpg', import.meta.url).href },
  { id: 'casamigos', name: 'Casamigos', description: 'A bold bottle selection for celebratory groups, curated hangouts, and confident lounge energy.', price: 250000, category: 'tequila', image: new URL('./assets/product-images/casamigos.jpg', import.meta.url).href },
  { id: 'patron', name: 'Patron', description: 'A bold bottle selection for celebratory groups, curated hangouts, and confident lounge energy.', price: 100000, category: 'tequila', image: new URL('./assets/product-images/patron.jpg', import.meta.url).href },
  { id: 'olmeca', name: 'Olmeca', description: 'A bold bottle selection for celebratory groups, curated hangouts, and confident lounge energy.', price: 50000, category: 'tequila', image: new URL('./assets/product-images/olmeca.jpg', import.meta.url).href },
  { id: 'sierra', name: 'Sierra', description: 'A bold bottle selection for celebratory groups, curated hangouts, and confident lounge energy.', price: 40000, category: 'tequila', image: new URL('./assets/product-images/sierra.jpg', import.meta.url).href },
  { id: 'azul-plata', name: 'Azul Plata', description: 'A bold bottle selection for celebratory groups, curated hangouts, and confident lounge energy.', price: 400000, category: 'tequila', image: new URL('./assets/product-images/azul-plata.jpg', import.meta.url).href },
  { id: 'azul-clase', name: 'Azul Clase', description: 'A bold bottle selection for celebratory groups, curated hangouts, and confident lounge energy.', price: 600000, category: 'tequila', image: new URL('./assets/product-images/azul-clase.jpg', import.meta.url).href },
  // Red Wine & Champagne
  { id: 'carlo-rossi', name: 'Carlo Rossi', description: 'A smooth wine and champagne choice for cultured gatherings, quiet celebrations, and elevated Backroom moments.', price: 25000, category: 'red-wine-champagne', image: new URL('./assets/product-images/carlo-rossi.jpg', import.meta.url).href },
  { id: '4-cousins', name: '4 Cousins', description: 'A smooth wine and champagne choice for cultured gatherings, quiet celebrations, and elevated Backroom moments.', price: 25000, category: 'red-wine-champagne', image: new URL('./assets/product-images/4-cousins.jpg', import.meta.url).href },
  { id: 'moet-rose', name: 'Moet Rose', description: 'A smooth wine and champagne choice for cultured gatherings, quiet celebrations, and elevated Backroom moments.', price: 200000, category: 'red-wine-champagne', image: new URL('./assets/product-images/moet-rose.jpg', import.meta.url).href },
  { id: 'belaire', name: 'Belaire', description: 'A smooth wine and champagne choice for cultured gatherings, quiet celebrations, and elevated Backroom moments.', price: 90000, category: 'red-wine-champagne', image: new URL('./assets/product-images/belaire.jpg', import.meta.url).href },
  { id: 'veuve-clicquot-rich', name: 'Veuve Clicquot Rich', description: 'A smooth wine and champagne choice for cultured gatherings, quiet celebrations, and elevated Backroom moments.', price: 250000, category: 'red-wine-champagne', image: new URL('./assets/product-images/veuve-clicquot-rich.jpg', import.meta.url).href },
  { id: 'martini-rose', name: 'Martini Rose', description: 'A smooth wine and champagne choice for cultured gatherings, quiet celebrations, and elevated Backroom moments.', price: 30000, category: 'red-wine-champagne', image: new URL('./assets/product-images/martini-rose.jpg', import.meta.url).href },
  // Beer, Soft Drinks & Water
  { id: 'heineken', name: 'Heineken', description: 'A familiar refreshment for relaxed visits, casual conversations, and everyday lounge comfort.', price: 5000, category: 'beer-soft-drinks-water', image: new URL('./assets/product-images/heineken.jpg', import.meta.url).href },
  { id: 'budweiser', name: 'Budweiser', description: 'A familiar refreshment for relaxed visits, casual conversations, and everyday lounge comfort.', price: 0, category: 'beer-soft-drinks-water', image: new URL('./assets/product-images/budweiser.jpg', import.meta.url).href },
  { id: 'coke', name: 'Coke', description: 'A familiar refreshment for relaxed visits, casual conversations, and everyday lounge comfort.', price: 1000, category: 'beer-soft-drinks-water', image: new URL('./assets/product-images/coke.jpg', import.meta.url).href },
  { id: 'fayrouz', name: 'Fayrouz', description: 'A familiar refreshment for relaxed visits, casual conversations, and everyday lounge comfort.', price: 2000, category: 'beer-soft-drinks-water', image: new URL('./assets/product-images/fayrouz.jpg', import.meta.url).href },
  { id: 'water', name: 'Water', description: 'A familiar refreshment for relaxed visits, casual conversations, and everyday lounge comfort.', price: 1_000, category: 'beer-soft-drinks-water', image: new URL('./assets/product-images/water.jpg', import.meta.url).href },
  { id: 'chivita-active', name: 'Chivita Active', description: 'A familiar refreshment for relaxed visits, casual conversations, and everyday lounge comfort.', price: 5000, category: 'beer-soft-drinks-water', image: new URL('./assets/product-images/chivita-active.jpg', import.meta.url).href },
  { id: 'hollandia-yoghurt', name: 'Hollandia Yoghurt', description: 'A familiar refreshment for relaxed visits, casual conversations, and everyday lounge comfort.', price: 5000, category: 'beer-soft-drinks-water', image: new URL('./assets/product-images/hollandia-yoghurt.jpg', import.meta.url).href },
  { id: 'cranberry', name: 'Cranberry', description: 'A familiar refreshment for relaxed visits, casual conversations, and everyday lounge comfort.', price: 10000, category: 'beer-soft-drinks-water', image: new URL('./assets/product-images/cranberry.jpg', import.meta.url).href },
  // Energy Drinks
  { id: 'power-horse', name: 'Power Horse', description: 'A crisp energy pick for late nights, lively groups, and moments that need an extra lift.', price: 3000, category: 'energy-drinks', image: new URL('./assets/product-images/power-horse.jpg', import.meta.url).href },
  { id: 'monster', name: 'Monster', description: 'A crisp energy pick for late nights, lively groups, and moments that need an extra lift.', price: 3000, category: 'energy-drinks', image: new URL('./assets/product-images/monster.jpg', import.meta.url).href },
  { id: 'red-bull', name: 'Red Bull', description: 'A crisp energy pick for late nights, lively groups, and moments that need an extra lift.', price: 3000, category: 'energy-drinks', image: new URL('./assets/product-images/red-bull.jpg', import.meta.url).href },
];



